name: "x"
version: "0.4.0"
usage: "Turn Kubernetes manifests and Kustomization into Helm Release"
description: "Turn Kubernetes manifests and Kustomization into Helm Release"
command: "$HELM_PLUGIN_DIR/bin/helm-x"
hooks:
  install: "$HELM_PLUGIN_DIR/install-binary.sh"
  update: "$HELM_PLUGIN_DIR/install-binary.sh"
