resources:
- apiVersion: v1
  kind: Pod
  metadata:
    name: foo
  spec:
    containers:
    - command:
      - sleep
      - 1000
      image: alpine:3.9.4
      imagePullPolicy: IfNotPresent
      name: foo
